export const LOAD_CAMPUSES = 'LOAD_CAMPUSES'
export const LOAD_STUDENTS = 'LOAD_STUDENTS'
export const ADD_CAMPUS = 'ADD_CAMPUS'
export const ADD_STUDENT = 'ADD_STUDENT'
export const DELETE_CAMPUS = 'DELETE_CAMPUS'
export const DELETE_STUDENT = 'DELETE_STUDENT'

